name: Build

on:
  pull_request:
    branches: [ master ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_USE_POLLING_FILE_WATCHER: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache NuGet Packages
      uses: actions/cache@v4
      with:
        key: nuget-cache
        path: ~/.nuget/packages
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8

    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src -c Release --no-restore
    - name: Test
      run: dotnet test ./src -c Release --no-build --verbosity normal
